In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("done_data.csv")

In [32]:
df

,Unnamed: 0,datadate,tic,adjcp,open,high,low,volume,macd,rsi,cci,adx,turbulence
0,0,20090102,AAPL,12.964286,12.268571,13.005714,12.165714,26641980.0,0.000000,100.000000,66.666667,100.000000,0.000000
1,1,20090102,AXP,19.330000,18.570000,19.520000,18.400000,10955620.0,0.000000,100.000000,66.666667,100.000000,0.000000
2,2,20090102,BA,45.250000,42.800000,45.560000,42.780000,7010171.0,0.000000,100.000000,66.666667,100.000000,0.000000
3,3,20090102,CAT,46.910000,44.910000,46.980000,44.710000,7116726.0,0.000000,0.000000,66.666667,100.000000,0.000000
4,4,20090102,CSCO,16.960000,16.410000,17.000000,16.250000,40977480.0,0.000000,100.000000,66.666667,100.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
90703,90703,20200817,WBA,41.175000,41.910000,41.969400,40.810000,5258868.0,0.092803,48.564939,40.646766,13.658417,128.294904
90704,90704,20200817,WMT,135.600000,134.350000,136.130000,133.850000,12991970.0,1.531932,61.371397,201.149482,52.305705,128.294904
90705,90705,20200817,XOM,42.640000,43.170000,43.170000,42.470000,15527400.0,-0.227324,46.511293,-65.015760,2.021414,128.294904
90706,90706,20200818,DJI,27778.070313,27853.480469,27891.119141,27668.789063,276170000.0,438.616391,58.958692,112.847474,28.548454,0.000000
90707,90707,20200819,DJI,27692.880859,27811.259766,27920.419922,27647.669922,311460000.0,418.046382,58.299839,100.123111,29.414148,0.000000

In [33]:
df = df[df.tic=='DJI']

In [34]:
df = df.drop(columns = ['Unnamed: 0'])

In [35]:
df

,datadate,tic,adjcp,open,high,low,volume,macd,rsi,cci,adx,turbulence
8,20090102,DJI,9034.690430,8772.250000,9065.280273,8760.780273,213700000.0,0.000000,0.000000,66.666667,100.000000,0.000000
39,20090105,DJI,8952.889648,9027.129883,9034.370117,8892.360352,233760000.0,-1.835274,0.000000,66.666667,100.000000,0.000000
70,20090106,DJI,9015.099609,8954.570313,9088.059570,8940.950195,215410000.0,-0.409376,44.031836,100.000000,100.000000,0.000000
101,20090107,DJI,8769.700195,8996.940430,8996.940430,8719.919922,266710000.0,-8.610869,15.743557,-133.333333,62.968091,0.000000
132,20090108,DJI,8742.459961,8769.940430,8770.019531,8651.190430,226620000.0,-13.970109,14.661898,-120.516235,70.860502,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
90621,20200813,DJI,27896.720703,27922.509766,27986.099609,27789.779297,360160000.0,436.652226,59.947810,171.234756,37.417766,148.479210
90652,20200814,DJI,27931.019531,27828.929688,27977.810547,27759.390625,275540000.0,450.765859,60.115656,153.613085,35.885909,139.231664
90683,20200817,DJI,27844.910156,27970.050781,27999.810547,27816.400391,286860000.0,449.817492,59.468415,137.252502,36.434278,128.294904
90706,20200818,DJI,27778.070313,27853.480469,27891.119141,27668.789063,276170000.0,438.616391,58.958692,112.847474,28.548454,0.000000
90707,20200819,DJI,27692.880859,27811.259766,27920.419922,27647.669922,311460000.0,418.046382,58.299839,100.123111,29.414148,0.000000

In [36]:
for i in range(1, 21):
    for col in ['adjcp', 'open', 'high', 'low', 'volume', 'macd', 'rsi', 'cci', 'adx', 'turbulence']:
        df[col+str(i)] = df[col].shift(i, fill_value='-' )

In [37]:
df[20:].to_csv('done_data_rolling_window.csv')

In [38]:
df['adjcp'].values

array([ 9034.69043 ,  8952.889648,  9015.099609, ..., 27844.910156,
       27778.070313, 27692.880859])

In [39]:
set(df.columns)

{'adjcp',
 'adjcp1',
 'adjcp10',
 'adjcp11',
 'adjcp12',
 'adjcp13',
 'adjcp14',
 'adjcp15',
 'adjcp16',
 'adjcp17',
 'adjcp18',
 'adjcp19',
 'adjcp2',
 'adjcp20',
 'adjcp3',
 'adjcp4',
 'adjcp5',
 'adjcp6',
 'adjcp7',
 'adjcp8',
 'adjcp9',
 'adx',
 'adx1',
 'adx10',
 'adx11',
 'adx12',
 'adx13',
 'adx14',
 'adx15',
 'adx16',
 'adx17',
 'adx18',
 'adx19',
 'adx2',
 'adx20',
 'adx3',
 'adx4',
 'adx5',
 'adx6',
 'adx7',
 'adx8',
 'adx9',
 'cci',
 'cci1',
 'cci10',
 'cci11',
 'cci12',
 'cci13',
 'cci14',
 'cci15',
 'cci16',
 'cci17',
 'cci18',
 'cci19',
 'cci2',
 'cci20',
 'cci3',
 'cci4',
 'cci5',
 'cci6',
 'cci7',
 'cci8',
 'cci9',
 'datadate',
 'high',
 'high1',
 'high10',
 'high11',
 'high12',
 'high13',
 'high14',
 'high15',
 'high16',
 'high17',
 'high18',
 'high19',
 'high2',
 'high20',
 'high3',
 'high4',
 'high5',
 'high6',
 'high7',
 'high8',
 'high9',
 'low',
 'low1',
 'low10',
 'low11',
 'low12',
 'low13',
 'low14',
 'low15',
 'low16',
 'low17',
 'low18',
 'low19',
 'low2',
 'low20',
 'low3',
 'low4',
 'low5',
 'low6',
 'low7',
 'low8',
 'low9',
 'macd',
 'macd1',
 'macd10',
 'macd11',
 'macd12',
 'macd13',
 'macd14',
 'macd15',
 'macd16',
 'macd17',
 'macd18',
 'macd19',
 'macd2',
 'macd20',
 'macd3',
 'macd4',
 'macd5',
 'macd6',
 'macd7',
 'macd8',
 'macd9',
 'open',
 'open1',
 'open10',
 'open11',
 'open12',
 'open13',
 'open14',
 'open15',
 'open16',
 'open17',
 'open18',
 'open19',
 'open2',
 'open20',
 'open3',
 'open4',
 'open5',
 'open6',
 'open7',
 'open8',
 'open9',
 'rsi',
 'rsi1',
 'rsi10',
 'rsi11',
 'rsi12',
 'rsi13',
 'rsi14',
 'rsi15',
 'rsi16',
 'rsi17',
 'rsi18',
 'rsi19',
 'rsi2',
 'rsi20',
 'rsi3',
 'rsi4',
 'rsi5',
 'rsi6',
 'rsi7',
 'rsi8',
 'rsi9',
 'tic',
 'turbulence',
 'turbulence1',
 'turbulence10',
 'turbulence11',
 'turbulence12',
 'turbulence13',
 'turbulence14',
 'turbulence15',
 'turbulence16',
 'turbulence17',
 'turbulence18',
 'turbulence19',
 'turbulence2',
 'turbulence20',
 'turbulence3',
 'turbulence4',
 'turbulence5',
 'turbulence6',
 'turbulence7',
 'turbulence8',
 'turbulence9',
 'volume',
 'volume1',
 'volume10',
 'volume11',
 'volume12',
 'volume13',
 'volume14',
 'volume15',
 'volume16',
 'volume17',
 'volume18',
 'volume19',
 'volume2',
 'volume20',
 'volume3',
 'volume4',
 'volume5',
 'volume6',
 'volume7',
 'volume8',
 'volume9'}